sonar.projectKey=jbcjorge_mcp-argo
sonar.organization=jbcjorge
sonar.projectName=mcp-argo

sonar.sources=.
sonar.tests=.
sonar.test.inclusions=**/*_test.go
sonar.exclusions=**/*_test.go,reports/**

sonar.go.coverage.reportPaths=reports/coverage.out
sonar.go.tests.reportPaths=reports/junit.xml

sonar.qualitygate.wait=true
